config/routes.rb
# -*- encoding : utf-8 -*-

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root to: "accounts#index"
  root to: redirect('index.html')

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'} do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :agencies, controllers: {sessions: 'agencies/sessions', registrations: 'agencies/registrations'} do
    get '/agencies/sign_out' => 'devise/sessions#destroy'
  end

  get "profile", to: "users#profile"
  post "follow", to: "influencers#follow"
  post "unfollow", to: "influencers#unfollow"

  resources :accounts do
    get '/accounts/external_search' => 'accounts#index_youtube_account'
  end

  resources :users do
    resources :accounts
    resources :campaigns
  end

  resources :influencers, only: [:index, :show] do
    resources :videos
    resources :posts
    post 'refresh_snapshots', on: :member
  end

  resources :user_media_contents, only: [:update]
  namespace :admin do
    resources :users
  end

  namespace :graphs do
    resources :influencers do
      get 'youtube_subscribers', on: :member
      get 'youtube_views', on: :member
      get 'instagram_followers', on: :member
      get 'instagram_likes', on: :member
    end
    resources :videos do
      get 'views_fluctuation', on: :member
      get 'likes_fluctuation', on: :member
    end
    resources :posts do
      get 'likes_fluctuation', on: :member
    end
    resources :campaigns do
      get 'youtube_views', on: :member
      get 'posts_likes', on: :member
    end
  end

  namespace :v1 do
    resources :users, only: [:create, :show]
  end

  get '/youtube_categories', to: 'youtube_categories#index'
  get '/oauth/youtube_callback' => 'oauth/call_backs#youtube_handler'
  get '/oauth/instagram_callback' => 'oauth/call_backs#instagram_handler'

  require 'sidekiq/web'
  mount Sidekiq::Web => 'sidekiq'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'bonsai'
  end unless Rails.env.development?
end

app/models/influencer.rb
# -*- encoding : utf-8 -*-

class Influencer < ApplicationRecord
  extend FriendlyId
  include InfluencerRatios
  include InstagramInteractions
  include Snapshots
  include Score

  has_one :account
  has_many :followings
  has_many :profiles, through: :followings
  # validates :title, uniqueness: true
  after_create :compute_score

  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
        :title,
        [:title, :platform]
    ]
  end

  def create_or_update_snapshot
    latest_snapshot = self.account.account_snapshots.where('created_at > ?', Date.today.beginning_of_day)
    update_snapshot(self, latest_snapshot)
  end

  private

  # TODO move away from here
  def update_snapshot(influencer, latest_snapshot)
    delete_today_posts(influencer.account)
    capture_account_snapshot_immediately(influencer.account)
  end

  def delete_today_posts(account)
    account.account_snapshots.last.delete
    if account.type == 'InstagramAccount'
      PostSnapshot.where('created_at > ?', Date.today.beginning_of_day).delete_all
    else # YouTube
      VideoSnapshot.where('created_at > ?', Date.today.beginning_of_day).delete_all
    end
  end

  def capture_account_snapshot_immediately(account)
    if account.type == 'InstagramAccount'
      refresh_instagram(account)
    else
      refresh_youtube(account)
    end
  end

  def compute_score
    ComputeInfluencerScore.perform_in(10.minutes, self.id)
  end
end

app/controllers/graphs/influencers_controller.rb
# -*- encoding : utf-8 -*-

class Graphs::InfluencersController < Graphs::ApplicationController
  include DataSetFormatter
  before_action :set_influencer

  def youtube_subscribers
    data = @current_influencer.account.subscribers
    payload = item_data_set(data)
    render json: payload
  end

  def youtube_views
    data = @current_influencer.account.views
    payload = item_data_set(data)
    render json: payload
  end

  def instagram_followers
    data = @current_influencer.account.ig_subscribers
    payload = item_data_set(data)
    render json: payload
  end

  def instagram_likes
    data = @current_influencer.account.ig_likes
    payload = item_data_set(data)
    render json: payload
  end

  private

  def set_influencer
    @current_influencer = Influencer.friendly.find(params[:id])
  end
end

app/controllers/influencers_controller.rb
# -*- encoding : utf-8 -*-

class InfluencersController < ApplicationController
  include Follows

  def index
    if params[:title].present?
      @influencers = Influencer.where("title LIKE ?", "%#{params[:title]}%").includes(:account).order("score DESC")
    else
      @influencers = Influencer.all.includes(:account).order("score DESC")
    end
    if params[:platform].present?
      @influencers = Influencer.where(platform: params[:platform]).includes(:account).order("score DESC")
    end
  end

  def show
    @influencer = Influencer.friendly.find(params[:id])
    if @influencer.platform == 'YouTube'
      if !@influencer.account.nil?
        @youtube_account = @influencer.account
        @youtube_interaction_like_ratio = @influencer.youtube_interaction_like_ratio
        @youtube_interaction_dislike_ratio = @influencer.youtube_interaction_dislike_ratio
        @youtube_engagement_ratio = @influencer.youtube_engagement_ratio
        @subscribers_score = @influencer.subscribers_score.round(1)
        @views_score = @influencer.views_score.round(1)
        @engagement_score = @influencer.engagement_score.round(1)
        @influencer_score = ((@subscribers_score + @views_score + @engagement_score) / 3).round(1)
        @sponsored_content_ratio = @influencer.account.sponsored_content_ratio
        @sponsored_content_views = @influencer.account.sponsored_content_views
      end
    elsif @influencer.platform == "Instagram"
      @platform = @influencer.platform
      @posts = @influencer.account.posts.order('published_at DESC')
      @top_hashtags = top_10_hashtags(@influencer)
    end
  end

  def refresh_snapshots
    influencer = Influencer.friendly.find(params[:id])
    influencer.create_or_update_snapshot
    redirect_to influencer_path(influencer)
  end

  private
  def influencer_params
    params.permit(:influencer_id, :profile_id)
  end

  def top_10_hashtags(influencer)
    bundle = ""
    matcher= /(?:\s|^)(?:#(?!\d+(?:\s|$)))(\w+)(?=\s|$)/i
    influencer.account.posts.each do |post|
      if !post.description.nil?
        bundle +=  post.description
      end
    end
    hashtags_array = bundle.scan(matcher)
    hashtags_array.group_by{|i| i}.map{|k,v| [v.count, k] }.sort.reverse.first(10)
  end
end

app/views/influencers/_cards.html.haml
.cards-container
  - @influencers.where(platform: 'YouTube').first(2).each do |i|
    .card
      .top{style: "background-image: url(#{i.account.youtube_channel_thumbnail})"}
      .bottom
        %p= i.title
        %p= "#{number_to_human(i.account.videos.count)} videos"
        %p= "#{number_to_human(i.account.youtube_channel_view_count)} views"

app/views/influencers/_ig_influencer_cards.html.haml
%table.table.influencer-top-level-fields{style: "width: 49%; display: inherit"}
  %tbody{style: "background-color: white"}
    %tr
      %td
        - if @influencer.account.posts.count == 0
          %td "0 Posts"
        - else
          %td= "#{number_to_human(@influencer.account.posts.count)} posts"
    %tr
      %td
        - if @influencer.account.ig_follows.nil?
          %td -
        - else
          %td= "#{number_to_human(@influencer.account.ig_follows)} followers"

%table.table.influencer-top-level-fields{style: "width: 49%; display: inherit; float: right"}
  %tbody{style: "background-color: white"}
    %tr
      %td= "#{number_to_human(@influencer.likes)} likes"
    %tr
      %td= "#{number_to_human(@influencer.comments)} comments"

app/views/influencers/_instagram.html.haml
.container.wide-container
  .test-c{style: "display: inline-block; text-align: right; padding-bottom: 10px; width: 100%"}
    .link-to-posts{style: 'display: inherit'}
      = link_to('Posts', influencer_posts_path(@influencer), class: 'btn btn-primary')
    .link-to-capture-snap{style: 'display: inherit'}
      = form_tag(refresh_snapshots_influencer_path(@influencer), :method => 'post') do
        = button_tag('Capture Snapshot', type: :submit, :name => nil, class: 'btn btn-default')

.panel.influencer-show-parent
  .panel-body.influencer-show-panel
    .container.wide-container
      %table.table.influencer-top-level-fields
        %tbody
          %tr
            - if @influencer.account.ig_profile_picture
              %td.borderless= image_tag @influencer.account.ig_profile_picture, class: 'ig-profile-image'
            - else
              %td.borderless -
            %td.borderless
              %h5
                .influencer-title{style: 'display: inline-block'}
                  = @influencer.title
                - if @influencer.account.account_snapshots.any?
                  .last-time-updated{style: 'display: inline-block; font-style: italic; font-size: 0.5em; vertical-align: middle;'}
                    = "(last time updated: #{distance_of_time_in_words(DateTime.now, @influencer.account.account_snapshots.last.created_at)} ago)"

      .table-influencer-info-container{style: 'display: inline-block; width: 100%'}
        = render 'ig_influencer_cards'

.container.wide-container{style: 'padding-bottom: 40px'}
  %h5 Top Hashtags
  - @top_hashtags.each do |block|
    .chip{style: 'background-color: #26a69a; color: white'}= "#{block[1].first}  x#{block[0]}"

.container.wide-container
  .graph-md{style: 'width: 49%; position: relative; display: inline-block'}
    %canvas#instagram-followers{style: 'position: relative; display: inline-block;'}
  .graph-md{style: 'width: 49%; position: relative; display: inline-block'}
    %canvas#instagram-likes{style: 'position: relative; display: inline-block;'}

:javascript
  $(document).ready(function() {
    drawInstagramFollowers($("#instagram-followers"))
    drawInstagramLikes($("#instagram-likes"))
  })


.container.wide-container.ig-latest-media
  %table.table.fz-table
    %thead
      %tr
        %td{colspan: 3}
        %td.right likes
        %td.right comments
    %tbody
      - if @influencer.account.posts.any?
        - @influencer.account.posts.order('published_at DESC').first(50).each do |post|
          %tr
            - if post.standard_res_image.nil?
              %td.fz-far__left -
            - else
              %td.fz-far__left= link_to image_tag(post.standard_res_image, size: "40x40", alt: "deleted"), influencer_post_path(@influencer, post), class: 'ig-post-image'
            - if post.description.nil?
              %td -
            - else
              %td{style: 'width: 70%'}= post.description
            - if post.ig_code.nil?
              %td -
            - else
              %td= link_to 'view on instagram', "https://www.instagram.com/p/#{post.ig_code}", target: :_blank
            %td.right= "#{post.like_count}"
            %td.right= "#{post.comment_count}"
      - else
        %tr
          %td{colspan: 4}

app/views/influencers/_youtube.html.haml
.container.wide-container
  .test-c{style: "display: inline-block; text-align: right; padding-bottom: 10px; width: 100%"}
    .link-to-posts{style: "display: inherit"}
      = link_to("Videos", influencer_videos_path(@influencer), class: "btn")
    .link-to-capture-snap{style: "display: inherit"}
      = form_tag(refresh_snapshots_influencer_path(@influencer), :method => "post") do
        = button_tag("Capture Snapshot", type: :submit, :name => nil, class: "btn")

.panel.influencer-show-parent
  .panel-body.influencer-show-panel
    .container.wide-container
      %table.table.card__influencer--detail-table
        %tbody
          %tr
            %td.borderless= image_tag(@youtube_account.youtube_channel_thumbnail)
            %td.borderless
              %h5
                = @youtube_account.youtube_channel_title
                - if @influencer_score < 2.0
                  .score-red
                    = @influencer_score
                - if @influencer_score > 6.0
                  .score-green
                    = @influencer_score
                - elsif @influencer_score > 2.0 && @influencer_score < 6.0
                  .score-yellow
                    = @influencer_score
                .last-time-updated{style: 'display: inline-block; font-style: italic; font-size: 0.5em; vertical-align: middle;'}
                  = "(last time updated: #{distance_of_time_in_words(DateTime.now, @influencer.account.account_snapshots.last.created_at)} ago)"

      .cards__container
        = render 'yt_subtables'
    .container.wide-container
      .graph__social
        .positive{style: "width: #{(@youtube_interaction_like_ratio).round(0)}%"}
          = "#{@youtube_interaction_like_ratio.round(0)}%"
        .negative{style: "width: #{(@youtube_interaction_dislike_ratio).round(0)}%"}
          = "#{@youtube_interaction_dislike_ratio.round(0)}%"

.container.wide-container
  .graph__md
    %canvas#new-subscribers
  .graph__md
    %canvas#new-visualizations

:javascript
  $(document).ready(function() {
    drawYoutubeViews($("#new-visualizations"))
    drawYoutubeSubscribers($("#new-subscribers"))
  })

.container.wide-container
  %table.table.fz-table

.container.wide-container.yt-latest-media
  %table.table.fz-table
    %thead
      %tr
        %td
        %td
        %td
        %td.right likes
        %td.right dislikes
        %td.right comments
    %tbody
      - if @influencer.account.videos.any?
        - @influencer.account.videos.order('published_at DESC').first(10).each do |video|
          - begin
            %tr
              %td.fz-far__left= link_to image_tag(Yt::Video.new(id: video.youtube_id).thumbnail_url), influencer_video_path(@influencer, video), class: 'yt-video-image'
              - if video.description.nil?
                %td -
              - else
                %td{style: "width: 70%"}= truncate(video.description, length: 81)  { link_to "see more", influencer_video_path(@influencer.id, video.id) }
              %td= link_to "view on youtube", "https://www.youtube.com/watch?v=#{video.youtube_id}", target: :_blank
              %td.right= "#{video.like_count}"
              %td.right= "#{video.dislike_count}"
              %td.right= "#{video.comment_count}"
            - rescue
      - else
        %tr
          %td{colspan: 4}

app/views/influencers/_yt_subtables.haml
%table.table.card__influencer--detail-table.card--right__half
  %tbody
    %tr
      %td.borderless{style: "width: 90%"} views
      %td.borderless.text-center
        = number_to_human @youtube_account.youtube_channel_view_count
      %td.borderless.text-center
        - if @views_score < 2.0
          .score-red
            = @views_score
        - if @views_score > 6.0
          .score-green
            = @views_score
        - elsif @views_score > 2.0 && @views_score < 6.0
          .score-yellow
            = @views_score
    %tr
      %td subscribers
      %td.borderless.text-center
        = number_to_human @youtube_account.youtube_channel_subscriber_count
      %td.borderless.text-center
        - if @subscribers_score < 2.0
          .score-red
            = @subscribers_score
        - if @subscribers_score > 6.0
          .score-green
            = @subscribers_score
        - elsif @subscribers_score > 2.0 && @subscribers_score < 6.0
          .score-yellow
            = @subscribers_score
    %tr
      %td engagement
      %td.borderless.text-center
        = "#{(@youtube_engagement_ratio).round(2)}%"
      %td.borderless.text-center
        - if @engagement_score < 1.0
          .score-red
            = @engagement_score
        - if @engagement_score > 3.0
          .score-green
            = @engagement_score
        - elsif @engagement_score > 1.0 && @engagement_score < 3.0
          .score-yellow
            = @engagement_score

%table.table.card__influencer--detail-table.card--left__half
  %tbody
    %tr
      %td.borderless{style: "width: 75%"} Category
      - if @influencer.account.category.nil?
        %td.borderless.text-center -
      - else
        %td.borderless.text-center= link_to @influencer.account.category, "/youtube_categories?category=#{Account.categories[@influencer.account.category]}"
    %tr
      %td.borderless Sponsored content
      %td.borderless
        .borderless.text-center= "#{@sponsored_content_ratio[:percentage]}% - #{@sponsored_content_ratio[:quantified_content]} videos"
    %tr
      %td.borderless sponsored content views
      %td.borderless
        .borderless.text-center= "#{number_to_human @sponsored_content_views} (#{((@sponsored_content_views.to_f / @youtube_account.youtube_channel_view_count) * 100).round(2)}%)"

app/views/influencers/index.html.haml
.container.container-fluid.wide-container
  .influencer-search
    = form_tag influencers_path, method: :get do
      = text_field_tag :title, nil, class: "form-control", placeholder: "Search..."

  = "#{link_to 'Instagram', "/influencers?platform=Instagram"} | #{link_to 'YouTube', "/influencers?platform=YouTube"}".html_safe

.row
  .col.s6
    .container.wide-container
      %ul.collection.with-header
        .collection-header
          %h5 Instagram
        - @influencers.each do |i|
          - if i.platform == 'Instagram'
            %li.collection-item.avatar
              - if i.account.ig_profile_picture.nil?
              - else
                = image_tag i.account.ig_profile_picture, class: 'circle'
              %span.title= link_to i.title, influencer_path(i)
              %p= "#{number_to_human(i.account.ig_follows)} followers"
              %p= "#{number_to_human(i.account.ig_overall_likes)} likes"
              .secondary-content
                - if current_user.profile.influencers.map(&:id).include?(i.id)
                  .btn.disabled watching
                - else
                  %td.right
                    = form_tag '/follow' do
                      = hidden_field_tag 'influencer_id', i.id
                      = submit_tag "watch", class: "btn waves-effect waves-light"
                      = hidden_field_tag 'user_id', current_user.id
  .col.s6
    .container.wide-container
      %ul.collection.with-header
        .collection-header
          %h5 Youtube
        - @influencers.each do |i|
          - if i.platform == 'YouTube'
            %li.collection-item.avatar
              = image_tag i.account.youtube_channel_thumbnail, style: 'width: 40px', class: 'circle'
              %span.title= link_to i.title, influencer_path(i)
              %p= "#{number_to_human(i.account.youtube_channel_subscriber_count)} subscribers"
              %p= "#{number_to_human(i.account.youtube_channel_view_count)} views"
              .secondary-content
                - if current_user.profile.influencers.map(&:id).include?(i.id)
                  .btn.disabled watching
                - else
                  %td.right
                    = form_tag '/follow' do
                      = hidden_field_tag 'influencer_id', i.id
                      = submit_tag "watch", class: "btn waves-effect waves-light"
                      = hidden_field_tag 'user_id', current_user.id

app/views/influencers/show.html.haml
= render @influencer.platform.downcase