config/routes.rb
# -*- encoding : utf-8 -*-

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root to: "accounts#index"
  root to: redirect('index.html')

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'} do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :agencies, controllers: {sessions: 'agencies/sessions', registrations: 'agencies/registrations'} do
    get '/agencies/sign_out' => 'devise/sessions#destroy'
  end

  get "profile", to: "users#profile"
  post "follow", to: "influencers#follow"
  post "unfollow", to: "influencers#unfollow"

  resources :accounts do
    get '/accounts/external_search' => 'accounts#index_youtube_account'
  end

  resources :users do
    resources :accounts
    resources :campaigns
  end

  resources :influencers, only: [:index, :show] do
    resources :videos
    resources :posts
    post 'refresh_snapshots', on: :member
  end

  resources :user_media_contents, only: [:update]
  namespace :admin do
    resources :users
  end

  namespace :graphs do
    resources :influencers do
      get 'youtube_subscribers', on: :member
      get 'youtube_views', on: :member
      get 'instagram_followers', on: :member
      get 'instagram_likes', on: :member
    end
    resources :videos do
      get 'views_fluctuation', on: :member
      get 'likes_fluctuation', on: :member
    end
    resources :posts do
      get 'likes_fluctuation', on: :member
    end
    resources :campaigns do
      get 'youtube_views', on: :member
      get 'posts_likes', on: :member
    end
  end

  namespace :v1 do
    resources :users, only: [:create, :show]
  end

  get '/youtube_categories', to: 'youtube_categories#index'
  get '/oauth/youtube_callback' => 'oauth/call_backs#youtube_handler'
  get '/oauth/instagram_callback' => 'oauth/call_backs#instagram_handler'

  require 'sidekiq/web'
  mount Sidekiq::Web => 'sidekiq'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'bonsai'
  end unless Rails.env.development?
end

app/models/user.rb
# -*- encoding : utf-8 -*-

class User < ApplicationRecord
  include UsersMixin
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  has_many :campaigns
  belongs_to :agency
  after_create :assign_default_role, :create_profile, :generate_access_token


  def as_json(options = nil)
    super({ only: %i[id email access_token] }.merge(options || {}))
  end

  private

  def assign_default_role
    add_role(:newuser) if roles.blank?
  end

  def create_profile
    Profile.create(user: self)
  end

  def generate_access_token
    token = SecureRandom.urlsafe_base64(16)
    update_attributes(access_token: token)
  end
end

app/controllers/admin/users_controller.rb
# -*- encoding : utf-8 -*-
class Admin::UsersController < Admin::ApplicationController
  def index
    @user_count = User.count
  end

  def show
    @user = User.find(params[:id])
    @youtube_auth_url = Yt::Account.new(
      scopes: YOUTUBE_SCOPES,
      redirect_uri: YOUTUBE_REDIRECT_URI)
      .authentication_url
  end
end

app/controllers/users/confirmations_controller.rb
# -*- encoding : utf-8 -*-
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# -*- encoding : utf-8 -*-
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# -*- encoding : utf-8 -*-
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# -*- encoding : utf-8 -*-
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    valid_domain or return
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def valid_domain
    # TODO could be improved with regexp
    allowed_domains = /@brainasaservice.com/
    if params[:user][:email].match(allowed_domains).nil?
      redirect_to new_user_registration_path and return false
    end
    true
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# -*- encoding : utf-8 -*-
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# -*- encoding : utf-8 -*-
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-

class UsersController < ApplicationController
  before_action :user_is_admin, except: [:profile]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @youtube_auth_url = Yt::Account.new(
      scopes: YOUTUBE_SCOPES,
      redirect_uri: YOUTUBE_REDIRECT_URI).authentication_url
    @instagram_auth_url = Instagram.authorize_url(
      redirect_uri: INSTAGRAM_REDIRECT_URI
    )
  end

  def profile
    @profile = current_user.profile
  end

  def destroy
    @user = User.find(params[:id])
    redirect_to root_path if @user.destroy
  end

  private

  def user_is_admin
    redirect_to root_path unless current_user.has_role?(:admin)
  end
end

app/controllers/v1/users_controller.rb
class V1::UsersController < V1::ApplicationController
  skip_before_filter :verify_authenticity_token
  skip_before_filter :authenticate_user, only: [:create]

  def create
    user = User.new(user_params)
    render json: user.errors.messages, head: :unprocessable_entity unless user.save
  end

  def show
    return head :forbidden if @current_user.id != params[:id].to_i
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

app/views/users/index.html.haml
.container.wide-container
  %table.table.table-hover
    %thead
      %tr
        %td email
        %td roles
        %td
    %tbody
      - @users.includes(:users_roles, :roles).each do |u|
        %tr
          %td= link_to u.email, user_path(u)
          %td= u.roles.map(&:name).join(", ")
          - if current_user.admin?
            %td= link_to 'delete', user_path(u), method: :delete, class: "btn btn-danger btn-xs"

app/views/users/profile.html.haml
- unless current_user.agency.nil?
  %h5 Agency
  .row
    .col.s12
      %ul.collection
        %li.collection-item= current_user.agency.name

.row
  .col.s8
    %h5 Watching
    - if @profile.influencers.any?
      - @profile.influencers.includes(:account).each do |i|
        %ul.collection
          - if i.platform == 'YouTube'
            %li.collection-item.avatar
              = image_tag i.account.youtube_channel_thumbnail, style: 'width: 40px', class: 'circle'
              %span.title= link_to i.title, influencer_path(i)
              %p= "#{number_to_human(i.account.youtube_channel_subscriber_count)} subscribers"
              %p= "#{number_to_human(i.account.youtube_channel_view_count)} views"
              .secondary-content
                %td
                  = form_tag '/unfollow' do
                    = hidden_field_tag 'influencer_id', i.id
                    = hidden_field_tag 'user_id', current_user.id
                    = submit_tag 'remove', class: 'btn btn-default'
          - if i.platform == 'Instagram'
            %li.collection-item.avatar
              - if i.account.ig_profile_picture.nil?
              - else
                = image_tag i.account.ig_profile_picture, class: 'circle'
              %span.title= link_to i.title, influencer_path(i)
              %p= "#{number_to_human(i.account.ig_follows)} followers"
              %p= "#{number_to_human(i.account.ig_overall_likes)} likes"
              .secondary-content
                %td
                  = form_tag '/unfollow' do
                    = hidden_field_tag 'influencer_id', i.id
                    = hidden_field_tag 'user_id', current_user.id
                    = submit_tag 'remove', class: 'btn btn-default'
    - else
      .collection.with-header
        .collection-header.center
          = "Influencers you're following will appear here. #{link_to ' Start by adding some here.', influencers_path}".html_safe

  .col.s4
    %h5 Campaigns
    - if current_user.campaigns.any?
      .collection
        - current_user.campaigns.order("created_at DESC").each do |campaign|
          = link_to campaign.name, user_campaign_path(current_user, campaign), class: 'collection-item'
      .btn.center
        = link_to 'New campaign', new_user_campaign_path(current_user), style: 'color: white; text-decoration: none;'
    - else
      .collection.with-header
        .collection-header
          = "You have no campaigns running,  #{link_to 'create one now', new_user_campaign_path(current_user)}".html_safe

app/views/users/show.html.haml
.container.wide-container
  %h1{style: "margin: 10px"} #{link_to 'users', users_path} / #{@user.email}
  - if @user.email == current_user.email
    .sync_account_container{style: "display: inline-block"}
      .sync_account{style: "margin: 10px; display: inherit"}= link_to "Add YouTube account", @youtube_auth_url, class: "btn btn-success"
      .sync_account{style: "margin: 10px; display: inherit"}= link_to "Add Instagram account", @instagram_auth_url, class: "btn btn-success"

  %table.table
    %tbody
      %tr
        %td
          youtube auth token:
          = !@user.youtube_auth_token.nil? ? @user.youtube_auth_token : "empty"
      %tr
        %td
          instagram auth token:
          = !@user.instagram_auth_token.nil? ? @user.instagram_auth_token : "empty"