config/routes.rb
# -*- encoding : utf-8 -*-

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root to: "accounts#index"
  root to: redirect('index.html')

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'} do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :agencies, controllers: {sessions: 'agencies/sessions', registrations: 'agencies/registrations'} do
    get '/agencies/sign_out' => 'devise/sessions#destroy'
  end

  get "profile", to: "users#profile"
  post "follow", to: "influencers#follow"
  post "unfollow", to: "influencers#unfollow"

  resources :accounts do
    get '/accounts/external_search' => 'accounts#index_youtube_account'
  end

  resources :users do
    resources :accounts
    resources :campaigns
  end

  resources :influencers, only: [:index, :show] do
    resources :videos
    resources :posts
    post 'refresh_snapshots', on: :member
  end

  resources :user_media_contents, only: [:update]
  namespace :admin do
    resources :users
  end

  namespace :graphs do
    resources :influencers do
      get 'youtube_subscribers', on: :member
      get 'youtube_views', on: :member
      get 'instagram_followers', on: :member
      get 'instagram_likes', on: :member
    end
    resources :videos do
      get 'views_fluctuation', on: :member
      get 'likes_fluctuation', on: :member
    end
    resources :posts do
      get 'likes_fluctuation', on: :member
    end
    resources :campaigns do
      get 'youtube_views', on: :member
      get 'posts_likes', on: :member
    end
  end

  namespace :v1 do
    resources :users, only: [:create, :show]
  end

  get '/youtube_categories', to: 'youtube_categories#index'
  get '/oauth/youtube_callback' => 'oauth/call_backs#youtube_handler'
  get '/oauth/instagram_callback' => 'oauth/call_backs#instagram_handler'

  require 'sidekiq/web'
  mount Sidekiq::Web => 'sidekiq'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'bonsai'
  end unless Rails.env.development?
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  # TODO: use polymorphic associations here
  has_many :user_media_content
  has_many :posts, through: :user_media_content
  has_many :videos, through: :user_media_content

  # NOTE: related models such as post or video are automatically
  #               maintained / added with the back-linking strategy.

  validates :name, presence: true

  # TODO: abstract
  def views_fluctuation
    dataset = {}
    videos.each_with_index do |video, i|
      tmp = group_and_sum_video_attribute(video, 'view_count')
      dataset[i] = series_formatter_absolute(tmp)
    end
    dataset
  end

  # TODO: abstract
  def instagram_likes
    dataset = {}
    posts.each_with_index do |post, i|
      tmp = group_and_sum_post_attribute(post, 'like_count')
      dataset[i] = series_formatter_absolute(tmp)
    end
    dataset
  end

  # TODO: abstract
  def state
    if DateTime.now < start_date
      0
    elsif DateTime.now > start_date && DateTime.now < end_date
      1
    else
      2
    end
  end

  private

  # TODO: abstract
  def campaign_videos_view_count
    count = 0
    videos.each do |video|
      count += video.view_count
    end
    count
  end

  # TODO: abstract
  def group_and_sum_video_attribute(video, target_attributes)
    video.video_snapshots.where('created_at > ?', start_date - 1.days)
         .group("DATE_TRUNC('day', created_at)")
         .sum(target_attributes.to_sym)
         .sort
         .reverse
  end

  # TODO: abstract
  def group_and_sum_post_attribute(post, target_attributes)
    post.post_snapshots.where('created_at > ?', start_date - 1.days)
        .group("DATE_TRUNC('day', created_at)")
        .sum(target_attributes.to_sym)
        .sort
        .reverse
  end

  # TODO: abstract
  def series_formatter_absolute(raw_data)
    raw_data.each_with_index do |el, i|
      raw_data[i][0] = el[0].strftime('%d/%m/%y')
    end
  end
end

app/controllers/campaigns_controller.rb
# -*- encoding : utf-8 -*-

class CampaignsController < ApplicationController
  def create
    campaign = Campaign.new(campaign_params)
    campaign.user_id = params[:user_id]
    if campaign.save
      redirect_to profile_path
    else
      redirect_to new_user_campaign_path(current_user), :flash => { :validation => 'Title has to be present.' }
    end
  end

  def new
    @campaign = Campaign.new()
    @user = current_user
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def edit
    @campaign = Campaign.find(params[:id])
    @user = current_user
  end

  def update
    campaign = Campaign.find(params[:id])
    if campaign.update_attributes(campaign_params)
      redirect_to user_campaign_path(campaign)
    else
      head :unprocessable_entity
    end
  end

  private

  def campaign_params
    params.require(:campaign).permit(:name, :budget, :start_date,
                                     :end_date, :backlinks, :briefing,
                                     :comments, :post_ids => [], :video_ids => [])
  end
end

app/controllers/graphs/campaigns_controller.rb
class Graphs::CampaignsController < Graphs::ApplicationController
  include DataSetFormatter

  def youtube_views
    campaign = Campaign.find(params[:id])
    payload = campaign_data_set(campaign.views_fluctuation)
    payload[:influencers] = campaign.videos.includes(:youtube_account).map do |v|
      v.youtube_account.influencer.title
    end
    render json: { views: payload }, head: :ok
  end

  def posts_likes
    campaign = Campaign.find(params[:id])
    payload = campaign_data_set(campaign.instagram_likes)
    payload[:influencers] = campaign.posts.includes(:instagram_account).map do |v|
      v.instagram_account.influencer.title
    end
    render json: { views: payload }, head: :ok
  end
end

app/views/campaigns/_form.html.haml
.container.wide-container.row
  .col.s10.offset-s1
    - url = request.path_info
    - if url.include?('new')
      %h5 Creating a campaign
    - else
      %h5= "Editing: #{@campaign.name}"
    %br
    = simple_form_for [@user, @campaign] do |f|
      .form-group
        = f.label :name
        = f.text_field :name, type: 'text', class: 'form-control', autofocus: true, placeholder: 'Set a remarkable name for your campaign...'
      .form-group.wide-select
        = f.label 'Budget'
        = f.text_field :budget, class: 'form-control', placeholder: 'Decide how much 💰💰💰 you want to allocate...'
      .form-group.wide-select
        = f.label :campaign_briefing
        = f.text_area :briefing, type: 'text', class: 'form-control', placeholder: 'Prepare a briefing for the content creators'
      .form-group.wide-select
        = f.label :backlinks
        = f.text_area :backlinks, type: 'text', class: 'form-control', placeholder: 'Any traceable text that goes on the deliverable\'s description to notify Fluenza the deliverable belongs to this campaign...'
      .row
        .col.s6
          .form-group.wide-select
            = f.label 'start date'
            = f.text_field :start_date, class: 'datepicker', placeholder: 'start date'
        .col.s6
          .form-group.wide-select
            = f.label 'termination date'
            = f.text_field :end_date, class: 'datepicker', placeholder: 'termination date'
      %hr
      .form-group.wide-select
        = f.label :comments
        = f.text_area :comments, type: 'text', class: 'form-control', placeholder: 'Extra thoughts? here\'s the place...'
      .form-group.right
        = f.submit class: 'btn btn-success'

:javascript
  $('.datepicker').pickadate({
    selectMonths: true,
    selectYears: 3,
    today: 'Today',
    clear: 'Clear',
    close: 'Ok',
    closeOnSelect: false
  });

  $(document).ready(function() {
    $(".select-2-el").select2({multiple: true})
  });

app/views/campaigns/edit.html.haml
= render 'form'

app/views/campaigns/index.html.haml
- if current_user.campaigns.any?
  .collection
    - current_user.campaigns.each do |campaign|
      = link_to campaign.name, user_campaign_path(current_user, campaign), class: 'collection-item'

app/views/campaigns/new.html.haml
= render 'form'

app/views/campaigns/show.html.haml
.wide-container
  .row
    .col.s12
      .card.teal.lighten-5
        .card-content
          %span.card-title= @campaign.name
          - if @campaign.briefing.nil? || @campaign.briefing.empty?
            %p{style: 'font-style: italic; color: grey;'} add a briefing to this campaign.
          - else
            %p{style: 'font-style: italic; color: grey;'}= @campaign.briefing
        .card-action{style: 'text-align: right'}
          = link_to 'Edit', edit_user_campaign_path(current_user, @campaign)

- if @campaign.videos.any? || @campaign.posts.any?
  .graph-container.card-4{style: 'width: 100%; background-color: rgba(251, 251, 251, 0.83)'}
    .container.wide-container
      .graph__md{style: 'width: 49%'}
        %canvas#campaign-visualizations
      .graph__md{style: 'width: 49%'}
        %canvas#campaign-posts-likes

:javascript
  $(document).ready(function() {
    drawCampaignVideoVisualizations($("#campaign-visualizations"))
    drawCampaignPostLikes($("#campaign-posts-likes"))
  })
  $( function() {
    $( "#posts-accordion" ).accordion({
      collapsible: true,
      active: false
    });
    $( "#videos-accordion" ).accordion({
      collapsible: true,
      active: false
    });
  } );

%br
- if @campaign.videos.any?
  .campaign-video-components.card-4{style: 'padding: 3px; border-radius: 5px'}
    .videos.accordion#videos-accordion
      - @campaign.user_media_content.where.not(video_id: nil).includes(:video).order('created_at DESC').each do |video_join|
        .header__container{style: 'width: 100%; display: inline-block'}
          .title{style: 'width: 49%; display: inherit; margin: 0 auto'}
            %p= 'Video'
            %p= video_join.video.title
          .stats{style: 'width: 49%; display: inherit; text-align: right'}
            %p= "#{number_to_human(video_join.video.view_count)} views"
            %p= "#{number_to_human(video_join.video.like_count)} likes"
        .form-inline{style: 'width: 100%'}
          = form_for video_join, remote: true do |f|
            = f.label :budget
            = f.text_field :budget, class: 'form-control input-group mb-2 mr-sm-2 mb-sm-0'
            = f.label :annotations
            = f.text_field :annotations, class: 'form-control input-group mb-2 mr-sm-2 mb-sm-0'
            .btn.btn-warning{ id: "vj_#{video_join.id}", onclick: "submitPartial($(this), vj_#{video_join.id});" } update
%br
- if @campaign.posts.any?
  .campaign-post-components.card-4{style: 'padding: 3px; border-radius: 5px'}
    .posts.accordion#posts-accordion
      - @campaign.user_media_content.where.not(post_id: nil).includes(:post).order('created_at DESC').each do |post_join|
        .header__container{style: 'width: 100%; display: inline-block'}
          .title{style: 'width: 49%; display: inherit; margin: 0 auto'}
            %p= 'Post'
            - if post_join.post.description.nil?
              %p= '-'
            - else
              %p= post_join.post.description
          .stats{style: 'width: 49%; display: inherit; text-align: right'}
            %p= "#{number_to_human(post_join.post.like_count)} likes"
            %p= "#{number_to_human(post_join.post.comment_count)} comments"

        .form-inline{style: 'width: 100%'}
          = form_for post_join, method: :patch, remote: true do |f|
            = f.label :budget
            = f.text_field :budget, class: 'form-control input-group mb-2 mr-sm-2 mb-sm-0'
            = f.label :annotations
            = f.text_field :annotations, class: 'form-control input-group mb-2 mr-sm-2 mb-sm-0'
            .btn.btn-warning{ id: "vj_#{post_join.id}", onclick: "submitPartial($(this), vj_#{post_join.id});" } update

:javascript
  var submitPartial = function(form, target){
    $('#' + target.id).removeClass("btn-warning")
    target.innerHTML = "updated"
    form.submit()
    $('#' + target.id).addClass("btn-success")
  }