config/routes.rb
# -*- encoding : utf-8 -*-

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root to: "accounts#index"
  root to: redirect('index.html')

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'} do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :agencies, controllers: {sessions: 'agencies/sessions', registrations: 'agencies/registrations'} do
    get '/agencies/sign_out' => 'devise/sessions#destroy'
  end

  get "profile", to: "users#profile"
  post "follow", to: "influencers#follow"
  post "unfollow", to: "influencers#unfollow"

  resources :accounts do
    get '/accounts/external_search' => 'accounts#index_youtube_account'
  end

  resources :users do
    resources :accounts
    resources :campaigns
  end

  resources :influencers, only: [:index, :show] do
    resources :videos
    resources :posts
    post 'refresh_snapshots', on: :member
  end

  resources :user_media_contents, only: [:update]
  namespace :admin do
    resources :users
  end

  namespace :graphs do
    resources :influencers do
      get 'youtube_subscribers', on: :member
      get 'youtube_views', on: :member
      get 'instagram_followers', on: :member
      get 'instagram_likes', on: :member
    end
    resources :videos do
      get 'views_fluctuation', on: :member
      get 'likes_fluctuation', on: :member
    end
    resources :posts do
      get 'likes_fluctuation', on: :member
    end
    resources :campaigns do
      get 'youtube_views', on: :member
      get 'posts_likes', on: :member
    end
  end

  namespace :v1 do
    resources :users, only: [:create, :show]
  end

  get '/youtube_categories', to: 'youtube_categories#index'
  get '/oauth/youtube_callback' => 'oauth/call_backs#youtube_handler'
  get '/oauth/instagram_callback' => 'oauth/call_backs#instagram_handler'

  require 'sidekiq/web'
  mount Sidekiq::Web => 'sidekiq'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'admin' && password == 'bonsai'
  end unless Rails.env.development?
end

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container
    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li.navbar-right= link_to 'Logout', destroy_user_session_path, method: :delete
      %p.navbar-text.navbar-right= "Signed in as #{current_user.email}"
    %ul.nav.navbar-nav
      %li= link_to 'Users', users_path
      %li= link_to 'Accounts', accounts_path

app/views/layouts/_side_navigation.html.haml
.fz--side_navigation
  .fz--side_navigation_title.fluenza-title Fluenza
  .fz--side_navigation_container
    .fz--side_navigation_link.profile_path_redirect{class: ('active' if current_page?(profile_path))}
      %span.icon-home.navbar-icon
      Profile
      .arrow
    .fz--side_navigation_link.accounts_path_redirect{class: ('active' if current_page?(accounts_path))}
      %span.icon-rocket.navbar-icon
      Explore
      .arrow
    .fz--side_navigation_link.influencers_path_redirect{class: ('active' if current_page?(influencers_path))}
      %span.icon-star.navbar-icon
      Influencers
      .arrow
    .fz--side_navigation_link
      %span.icon-social-youtube.navbar-icon
      YouTube
    .fz--side_navigation_link_sub.categories_path_redirect{class: ('active' if current_page?(youtube_categories_path))}
      %span.icon-list.navbar-icon
      Categories
      .arrow
    - if current_user.has_role?(:admin)
      .fz--side_navigation_link.users_path_redirect{class: ('active' if current_page?(users_path))}
        %span.icon-cup.navbar-icon
        Users
        .arrow
      .fz--side_navigation_link.admin_path_redirect
        %span.icon-wrench.navbar-icon
        Admin
        .arrow

app/views/layouts/_top_navbar.html.haml
.nav-wrapper
  = link_to 'Fluenza', root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Fluenza
    %meta{property: "og:image", content: "/ms-icon-144x144.png"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/humanize-plus/1.8.2/humanize.min.js'
  %body
    - if user_signed_in?
      .navbar-fixed
        .row
          %nav
            .nav-wrapper.teal.darken-3
              .col.s12
                = link_to 'Fluenza', root_path, class: 'brand-logo'
                %ul.right
                  %li= link_to 'Explore', accounts_path, class: 'fz-custom-navbar'
                  %li= link_to 'Influencers', influencers_path, class: 'fz-custom-navbar'
                  %li= link_to 'Campaigns', user_campaigns_path(current_user), class: 'fz-custom-navbar'
                  %li= link_to 'Profile', profile_path, class: 'fz-custom-navbar'
                  - if user_signed_in?
                    %li= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'fz-custom-navbar'
                    = "Signed in as #{current_user.email}"
    %br
    .container.wide-container
    = yield